# Generated by Django 4.0.6 on 2022-07-31 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ELIMINADO', 'Eliminado')], default='PENDIENTE', max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('refCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('refRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
