# Generated by Django 4.0.6 on 2022-07-31 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=255)),
                ('razonSocial', models.CharField(max_length=255)),
                ('expedidoDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('methodPay', models.CharField(max_length=255)),
                ('refFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
                ('refReserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserve')),
            ],
        ),
    ]
